### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by glaukiol1** [SpectreTechnologiesLLC/chatterbocs#7]
# Font

We need a new and good font in Chatterbocs, this is perfect for someone who doesnt want to code! If you want, you can also add the font yourself in `public/css/layout.css`, or just comment the link to the Google Font below. Any help would be amazing! Thanks!

**Comment by marcotduenas** [comment]
https://fonts.google.com/specimen/Roboto+Mono

**Comment by glaukiol1** [comment]
@marcotduenas, thank you! Our designer liked the font very much, thanks!
